<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function clotya_child_enqueue_styles() {
    wp_enqueue_style( 'parent-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'clotya-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'clotya-style' ),
        wp_get_theme()->get('Version')
    );
}

add_action(  'wp_enqueue_scripts', 'clotya_child_enqueue_styles', 99 );











// 🎅 Enable Christmas Mode (temporary)
add_action('wp_enqueue_scripts', 'clotya_christmas_mode');
function clotya_christmas_mode() {
    // Load extra Christmas CSS + JS
    wp_enqueue_style('christmas-style', get_stylesheet_directory_uri() . '/christmas.css', array(), '1.0');
}


// Update wishlist link in header/footer to point correctly
function arham_update_wishlist_link_in_header() {
    ?>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        const wishlistBtn = document.querySelector('.wishlist-button');
        if (wishlistBtn) {
            wishlistBtn.setAttribute('href', '<?php echo esc_url(home_url('/wishlist')); ?>');
        }
    });
    </script>
    <?php
}
add_action('wp_footer', 'arham_update_wishlist_link_in_header');

// === End Wishlist Feature ===

function fix_clotya_wishlist_page() {
    $wishlist_page = get_page_by_path('wishlist');
    if ($wishlist_page) {
        set_theme_mod('clotya_wishlist_page', $wishlist_page->ID);
    }
}
add_action('after_setup_theme', 'fix_clotya_wishlist_page');
