<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function clotya_child_enqueue_styles() {
    wp_enqueue_style( 'parent-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'clotya-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'clotya-style' ),
        wp_get_theme()->get('Version')
    );
}

add_action(  'wp_enqueue_scripts', 'clotya_child_enqueue_styles', 99 );



// 🎅 Enable Christmas Mode (temporary)
add_action('wp_enqueue_scripts', 'clotya_christmas_mode');
function clotya_christmas_mode() {
    // Load extra Christmas CSS + JS
    wp_enqueue_style('christmas-style', get_stylesheet_directory_uri() . '/christmas.css', array(), '1.0');
}

// Add snowflake effect site-wide (no plugin)
function add_snow_effect_files() {
    // Enqueue CSS
    wp_enqueue_style('snow-style', get_stylesheet_directory_uri() . '/snow.css', array(), null);

    // Enqueue JS (footer mein load)
    wp_enqueue_script('snow-script', get_stylesheet_directory_uri() . '/snow.js', array(), null, true);
}
add_action('wp_enqueue_scripts', 'add_snow_effect_files');


//Christmas end 🎅

// Update wishlist link in header/footer to point correctly
function arham_update_wishlist_link_in_header() {
    ?>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        const wishlistBtn = document.querySelector('.wishlist-button');
        if (wishlistBtn) {
            wishlistBtn.setAttribute('href', '<?php echo esc_url(home_url('/wishlist')); ?>');
        }
    });
    </script>
    <?php
}
add_action('wp_footer', 'arham_update_wishlist_link_in_header');

// === End Wishlist Feature ===

function fix_clotya_wishlist_page() {
    $wishlist_page = get_page_by_path('wishlist');
    if ($wishlist_page) {
        set_theme_mod('clotya_wishlist_page', $wishlist_page->ID);
    }
}
add_action('after_setup_theme', 'fix_clotya_wishlist_page');



// === Force show username field on WooCommerce registration form ===
add_filter( 'woocommerce_registration_generate_username', '__return_false' );

// === Ensure WooCommerce registration form includes username field ===
add_filter( 'woocommerce_register_form_start', function() {
    ?>
    <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
        <label for="reg_username"><?php esc_html_e( 'Username', 'woocommerce' ); ?>&nbsp;<span class="required">*</span></label>
        <input type="text" class="woocommerce-Input woocommerce-Input--text input-text" name="username" id="reg_username" autocomplete="username" value="<?php echo (!empty($_POST['username']) ? esc_attr(wp_unslash($_POST['username'])) : ''); ?>" required />
    </p>
    <?php
});